### ISSUE TITLE
Bearro - Bug/ Issue : Import button not working

### ISSUE THREAD

**Issue by bearro** [Gravium/gravium-desktop#14]
Tag:Bearro - Bug/ Issue
Detailed Description:
when load file and click import button it does nothing. I am trying to import a encrypted file.
Attachment: https://dl.airtable.com/.attachments/463f917e34190e3156d0171b1fc8b0f9/1bd1c030/Capture.JPG
Type Of Report:Bug/ Issue
Troubled Feature:Import Process
Gravium Address(If Applies): None
Error Code(If Applies):None

**Comment by Japangeek** [comment]
Fixed
