### ISSUE TITLE
Bug in wallet unlock feature

### ISSUE THREAD

**Issue by bearro** [Gravium/gravium-desktop#4]
Bug:
- When unlocking wallet after you enter your password pressing the Enter key doesn't work
Other Idea:
- Maybe change seconds to minutes for unlock period

**Comment by Japangeek** [comment]
Changing seconds to minutes for unlock period will updated sometimes in the future. So then it can show days, hours, minutes and seconds depending how high the timeout is. And also I think this deserve own issue.

**Comment by Japangeek** [comment]
Enter key is now working.
