### ISSUE TITLE
Continue improving wallet import using wallet.dat (future)

### ISSUE THREAD

**Issue by bearro** [Gravium/gravium-desktop#6]
Continue discussing and exploring if theres a way we can just use wallet.dat for import and get complete control of all corresponding wallet address history without need for 'dumpwallet' command for users safety in the future as to only work with files that have ability to be encrypted and to make updates and wallet restoration seamless.

**Comment by Japangeek** [comment]
If someone have a idea how to import wallet.dat by using node, then I would be grateful if you could write here for a solution.

wallet.dat is based on berkeley db 4.8

Some packages is either way too outdated and wont work so well or some of them doesnt support the "cursor" feature which is very important for wallet.dat.

**Comment by Japangeek** [comment]
Got another solution. You can import wallet.dat now directly.
Import process is now even faster, instead loading 3-4 mins its now 6-8 secs fast.
