### ISSUE TITLE
Add total gravium in send tab like in overview tab (unconfirmed + confirmed) 

### ISSUE THREAD

**Issue by bearro** [Gravium/gravium-desktop#9]
Add total gravium in send tab like in overview tab (unconfirmed + confirmed) this will be the third item on the top center. 

This will help eliminate confusion when sending to yourself, currently appears like you loose your GRV which can by scary.

**Comment by Japangeek** [comment]
Instead confirmed+unconfirmed, it will now show together aka as Total Balance. Fixed
